### ISSUE TITLE
About the mask_size and step_size

### ISSUE THREAD

**Issue by Acmenwangtuo** [vqdang/hover_net#114]
in infer.py, before you infer you should crop the 1000x1000x3 image to some small patches,but I can see that in the code have mask shape and step size and window size , what the different from mask shape and step shape?

**Comment by simongraham** [comment]
Mask shape is the size of the output of the network. Therefore it is also the size of the mask used during training. The mask is the ground truth. The step size can also be named the 'stride'. It controls how many pixels to move each time when extracting patches during inference. Here, we set the step size equal to the mask size so that we make a prediction once per input pixel. Note, the stride must always be <= mask size otherwise some pixels will not have a corresponding prediction (and I suspect it may give you an error). If the step_size < mask_size, then you will have overlapping patches that will need to be dealt with. In this code, we only work with the situation where mask_size = step_size. 

The window size is the size of the input to the network. In HoVer-Net this is larger than the output size (equal to mask size) because we do not use padded convolution in the upsampling branches.

**Comment by Acmenwangtuo** [comment]
Thank you, I writer the code as you see,and i get the true predict!
