### ISSUE TITLE
Compute Statistics for PanNuke Dataset

### ISSUE THREAD

**Issue by nauyan** [vqdang/hover_net#144]
Hi @vqdang and @simongraham 

I have converted PanNuke dataset to the format of CoNSeP from which I have been able to train and test. However, I am unable to run the compute_stats.py script that needs Ground Truth in the form of .mat files. Can you please advise regarding what should be done moving forward?

**Comment by simongraham** [comment]
Hi @nauyan ,

You can either convert the ground truth or the code so that it works for your purpose. It is up to you what you decide 👍🏼. If you wish to use this repo for stat calculation, then I would advise converting the PanNuke data to appropriate `mat` files and check out the `compute_stats.py` so that you know how to save it. If you plan to use the evaluation code used in the PanNuke paper, then you may want to do things slightly differently. For that, take a look at[ this repo](https://github.com/TIA-Lab/PanNuke-metrics).

**Comment by nauyan** [comment]
@simongraham Got it. Thanks
