### ISSUE TITLE
WSI predicts problems

### ISSUE THREAD

**Issue by kiven1213** [vqdang/hover_net#151]
Hi，@simongraham和@vqdang   
I have some problems when making WSI prediction, and I want to ask you for advice.
![A0~P K 80_9~F%(K7V{E7H8](https://user-images.githubusercontent.com/37852705/127250451-d04a01d4-45a3-4d47-bc2d-36d9f28891d3.png)
![image](https://user-images.githubusercontent.com/37852705/127250489-2b174a27-4369-43cc-ae49-426cfb1ecab8.png)
![image](https://user-images.githubusercontent.com/37852705/127250526-3b2ae1cc-d244-455a-8a0e-4afcec549127.png)

**Comment by simongraham** [comment]
Hi,

Please can you provide the specs of your system.

**Comment by vqdang** [comment]
The first error is due to the folder `1`. The code only deals with a root folder containing entirely WSI atm. You can see that the log has a line `Process: 1` , normally it would be `Process: [IMAGE_NAME`

The last error is coming from openslide. I have an  feeling this may be due to corrupt metadata or the code could not parse the input path correctly.  You can try open it alone in openslide and get back to use with the metadata.
