### ISSUE TITLE
Dice Score and Validation Strategy 

### ISSUE THREAD

**Issue by YashSharma** [vqdang/hover_net#160]
Hello Authors,

Thanks for your contributions and for making code opensource with detailed instructions. It is super helpful. I have two questions regarding validation and will greatly appreciate the response:
1. In the paper, which dice score is reported - dice score 1 or dice score 2? Since in the compute_stats.py, dice score 1 is getting calculated, but in the paper ensemble dice (dice score 2) is mentioned.
2. For the HoVer-Net experiment on CoNSep data and final reporting, how were the 41 H&E divided into training, validation, and testing? Currently, only two splits are present - train and validation, and final numbers are reported on validation. Also, the paper mentions no early stopping or conditional saving logic, so how the training logic of 50-50 epochs was finalized?
 
Thanks,
Yash

**Comment by simongraham** [comment]
Hi!

1) We don't use ensemble dice in the paper. We mention it, but don't use it due to the points we raise in the paper. The dice we report is standard dice score. 
2) You can divide your data as you wish, but for the paper we used the test as validation. This is why we had the extra generalisation experiment in Table 4. We used 50-50 because this a sufficient number of epochs to ensure that training had converged for each stage.

**Comment by YashSharma** [comment]
Hi Simon, 

Thanks for the response. It is super helpful for my experiment design. 

Regards,
Yash

**Comment by caprioGirl** [comment]
> Hi!
> 
>     1. We don't use ensemble dice in the paper. We mention it, but don't use it due to the points we raise in the paper. The dice we report is standard dice score.
> 
>     2. You can divide your data as you wish, but for the paper we used the test as validation. This is why we had the extra generalisation experiment in Table 4. We used 50-50 because this a sufficient number of epochs to ensure that training had converged for each stage.

Does the same validation hold true for the Kumar dataset?
