### ISSUE TITLE
About src/loader/augs.py

### ISSUE THREAD

**Issue by GekFreeman** [vqdang/hover_net#17]
Thanks for your nice code!
I have two questions here:
1. The operation that expanding the box seems not considering the situation in which the instance is on the boundary of the image. (where -2 may be negative and +2 may be out of bounds).[Code Here](https://github.com/vqdang/hover_net/blob/6dc2868f98d640eea5398813c8a80f4d44d47c7e/src/loader/augs.py#L222)
2. And another question is that, after expanding the box, is there any need to check the size of the height and width of the bounding box? (Unless the instance is on the boundary, the minimal size of the bounding box would be 4x4)[Code Here](https://github.com/vqdang/hover_net/blob/6dc2868f98d640eea5398813c8a80f4d44d47c7e/src/loader/augs.py#L231)

**Comment by vqdang** [comment]
@GekFreeman Hi, 

1. The input patches for augmentation have been made (or asked to be made) so that they always have at least double the size the targetted size (i.e if inputting size for the network is 254x254, then during augmentation the patches size always 254x254 * a with a >= 2.0). You can see this mentioned in here https://github.com/vqdang/hover_net/blob/6dc2868f98d640eea5398813c8a80f4d44d47c7e/src/extract_patches.py#L28-L31 As a result, we don't really need to worry that the bboxes of the instance under our consideration (i.e instances within the central region during the augmentation) are out of bound.
2. I don't remember clearl but I would say that I put these lines there for sanity check. Because as mentioned in 1 and https://github.com/vqdang/hover_net/blob/6dc2868f98d640eea5398813c8a80f4d44d47c7e/src/loader/augs.py#L211 there shouldn't have any bboxes with size < 4x4 by that line. You can feedback to us if you see any problem once they are removed.

**Comment by simongraham** [comment]
Hi @GekFreeman,

Thanks for pointing this out. Because we only consider the central region at the output of the network, we don’t need to worry about instances at the edge of the original image. Refer to:

https://github.com/vqdang/hover_net/blob/master/src/config.py#L161

We see that this line will crop the horizontal and vertical map ground truth, disregarding nuclei at the edge. However, we shall still explore this problem and double check exactly what happens for these ‘edge nuclei’. They won’t have an effect on the performance, as discussed above, but we may clean up the code by dealing with this situation. 

For your second question, you are right - this was merely for a sanity check. 

We will reinform you when we have explored the above situation and afterwards close the issue.

**Comment by GekFreeman** [comment]
Hi @simongraham @vqdang , Thanks for your timely explanation,
For the first question, I just thought the code here was not robust because
```python
inst_box[0] -= 2
inst_box[2] -= 2
inst_box[1] += 2
inst_box[3] += 2

inst_map = inst_map[inst_box[0]:inst_box[1],
inst_box[2]:inst_box[3]]
```
`inst_box[0]` might be negative, at the same time, `inst_box[1]` could be positive (grammarly error).
However, I find the instances you are traversing here are only in the `crop_ann`, which is not possible at the edge of the original image(after `_fix_mirror_padding` and `cropping_center`).
The point you mentioned above does explain why they won't affect the performance.

For the second question, I will add to this issue if I have some problems when I delete the check.
Thanks again for your nice code~

**Comment by simongraham** [comment]
We have added a small comment at:

https://github.com/vqdang/hover_net/blob/master/src/loader/augs.py#L223

to help alleviate any confusion. We confirm that the bounding boxes are valid due to the consideration of the **central** part of the image.
