### ISSUE TITLE
On the study of Ablation

### ISSUE THREAD

**Issue by xiaoshuomin** [vqdang/hover_net#173]
I am trying to reproduce the ablation study of removing the NC branch, and my approach is to change the output of the NP branch to the nr_types. But there are two pieces of code that I don't know how to change. Please tell me what to do, thanks.

![1635915084(1)](https://user-images.githubusercontent.com/43821417/140011566-67463838-9b46-47aa-8236-e676043b5b02.jpg)
![1635915105(1)](https://user-images.githubusercontent.com/43821417/140011609-3942d626-9284-454a-94ed-1c35d719c16c.jpg)

**Comment by simongraham** [comment]
Hi - I am not sure exactly what you are trying to say with these code snippets. However, I will do my best to describe what you can do in terms of the change you described. 

In fact, I think it will be easier if you remove the NP branch rather than the NC branch. It is the same thing as you mentioned, but it will just be a bit more straight forward in terms of implementation. 

You will need to ensure you change `net_desc.py` to ensure that you now have 3 branches. You should remove the 'np' branch from [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/net_desc.py#L87). You will need to also remove everything relating to 'np' branch from `run_desc.py` and `opt.py`. 

During post processing, you can then get the same thing as NP by summing up all the positive channel predictions.

I hope this helps.

**Comment by xiaoshuomin** [comment]
My approach is to delete the NP branch, because in the structure of the hovernet, the structure of the three branches is the same, deleting the NP branch is equivalent to deleting the NC branch. But in the calculation of loss, 'msge_loss' needs to use the variable true_np_onehot for calculation. If the NP branch is deleted, the variable related to np should also be deleted. How should the code be replaced or modified?  thank you.https://github.com/vqdang/hover_net/blob/61ffeca6d22bba8aae0727523192150175be8b18/models/hovernet/run_desc.py#L41 https://github.com/vqdang/hover_net/blob/61ffeca6d22bba8aae0727523192150175be8b18/models/hovernet/run_desc.py#L73-L74

**Comment by vqdang** [comment]
I am not sure if you have resolved this. NC ground truth can be used to generate NP ground truth by combining all channel with index > 0 (which indicate the type of nuclei pixels). Then you will have the true_np_onehot.
