### ISSUE TITLE
crcHisto Dataset usage

### ISSUE THREAD

**Issue by Ghulam111** [vqdang/hover_net#18]
can i ask how you used the crcHisto dataset mentioned in the paper .The format of that dataset is much different from others.can you provide some helper code for setting up that dataset for HoverNet pipeline .

**Comment by simongraham** [comment]
Hi @Ghulam111 

For the CRCHisto dataset, only the point annotations are given. If you look into table 5, only PQ  uses the segmentation mask; other metrics are based on the distance to the centroid. For the CRCHisto dataset, we either apply SC-CNN or a segmentation model. SC-CNN is a detection method and therefore outputs the centroid prediction. For segmentation based methods, we calculate the centroid for each instance mask. Then the metrics can be calculated accordingly. 

It should be noted, that we never train on CRCHisto. We train on CoNSeP and process CRCHisto. We had to do this because the segmentation masks weren't available for CRCHisto. 

Let me know if this answers your question.

**Comment by Ghulam111** [comment]
ok i understand now

**Comment by simongraham** [comment]
Great- will close the issue.
