### ISSUE TITLE
CUDA isn't available

### ISSUE THREAD

**Issue by WandernForte** [vqdang/hover_net#190]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

====================
my machine is NOT a CPU-only machine.
here is terminal output
`>>> import torch
>>> torch.cuda.is_available()
True
>>> 
`

**Comment by WandernForte** [comment]
also, could you give a concrete example for run_infer.py ?

**Comment by vqdang** [comment]
You have to resolved the above error yourselves as it is more related to pytorch. Strictly speaking, [cuda not detected] can happen due to wrong runtime environment, especially when the IDEs (pycharm, visual code, etc.) involve. This can make your terminal using different environment compared to the one used by IDEs.

As for the how to use `run_infer.py`, we have already provided sample scripts.

https://github.com/vqdang/hover_net/blob/master/run_tile.sh
https://github.com/vqdang/hover_net/blob/master/run_wsi.sh
