### ISSUE TITLE
Increasig number of workers slows down inference!

### ISSUE THREAD

**Issue by Paulpal1990** [vqdang/hover_net#204]
Hi,

First, I would like to express my sincere appreciation to the creators of this amazing segmentation/classification pipeline. 
I just have one issue. It looks like when I run inference on WSIs, increasing the number of workers has the opposite affect on the processing time. For example, when I use 96 workers, it takes ">100" seconds to process one chunk, but when I use a single worker, it takes only ~4 seconds. Could anyone explain the reason for this? 

Thank you :)

**Comment by vqdang** [comment]
This is the limitation of python and the system you have. Typically, you should assign the number of workers <= number of virtual cores in your CPUs, even then, you should not assign everything because the system still needs to attend to stuffs that are not just your python code. Another thing is python workers are not as usual workers in C++ and thus it exaggerates some underlining communication problem between processes. This is a very naive and likely wrong summary though, you can read more on this
https://stackoverflow.com/questions/1970345/what-is-thread-contention
