### ISSUE TITLE
Can I run the model on MoNuSAC dataset

### ISSUE THREAD

**Issue by Michaelsqj** [vqdang/hover_net#30]
Can I run the model on MoNuSAC dataset? Since MoNuSAC dataset images have varied shapes and some are smaller than input patch 270*270, what pre-process is needed?

**Comment by simongraham** [comment]
This happens regularly in any computer vision task- you may get a dataset of variable size and you sometimes images will be smaller than your input. Typically, you may apply padding where you reflect the image at the borders so that the minimum size of an image is the size of your input. Then, you can extract patches as normal and use the model. 

This function in open cv should come in handy:

`img = np.lib.pad(img, ((padt, padb), (padl, padr)), 'reflect')`

where, `padt`, `padb`, `padl` and `padt
r` are the number of pixels to pad the original image at the top, bottom, left and right. 

The number of nuclei types will be the same that we have used for CoNSep (4 nuclei + 1 BG = 5).

**Comment by Michaelsqj** [comment]
Thank you so much for your detailed help! In addition, after I padded the images to be larger than 270*270 (even though the sizes of images are still different ), I can just follow the procedure in your Readme to train the model, am I correct?

**Comment by Michaelsqj** [comment]
Ps. In inferring stage, what does pred_map look like?  I still have trouble understanding how you assemble the pred_map of patches into image only by reshape. 
![image](https://user-images.githubusercontent.com/47425492/76268187-43381c80-62a8-11ea-9881-ffa0172ee8a5.png)

**Comment by simongraham** [comment]
Yes, once you have padded the images, you can use `extract_patches.py` to get the patches. Note, our network assumes input patches are HxWx5. i.e the first 3 channels are the RGB of the image, then the final 2 channels are the instance segmentation map and then the class map. i.e the instance segmentation map has pixels ranging from 0 to N, where 0 is the background and N is the number of nuclei. Then, the intra-nucleus pixel values are all the same, but the inter-nucleus values are all different. The class map has pixels ranging from 0 to C, where 0 is background and C is the number of classes. Then a pixel value denotes the class of that pixel.

You should organise your images in one directory, then your labels (2 channels- instance map and class map) in another directory. Then, the `extract_patches.py` will organise your patches into the above required form. Download the CoNSeP dataset and have a look at the labels if there is any confusion. 

In terms of the aggregation of the prediction, we first build a list of all the patch-level predictions and then we assemble these patches together to get the final prediction.

**Comment by simongraham** [comment]
I am closing this issue- we have made a few changes to make the code easier to run with external data. You can track issue #31 to see the commit history.

**Comment by Dogdog00** [comment]
> Thank you so much for your detailed help! In addition, after I padded the images to be larger than 270*270 (even though the sizes of images are still different ), I can just follow the procedure in your Readme to train the model, am I correct?

您好，我的图像是224*224的，我必须把它转化成270*270的吗？如果填充的话你用的哪种方法？
