### ISSUE TITLE
Use Mask-RCNN  to train CoNSeP dataset

### ISSUE THREAD

**Issue by GekFreeman** [vqdang/hover_net#40]
Hi, I am reproducing your work in your paper. And now, I have almost the results using the model hover_net. However, when I use Mask RCNN(just modify the anchor size and detection instances number) to train these datasets(CoNSeP/Kumar/CPM17)，I get the much worse result compared with yours. Could you help me with more details about how did you implement Mask RCNN to train these three datasets?
Thanks~

**Comment by simongraham** [comment]
Hi @GekFreeman ,

Yes, Mask-RCNN can be a bit fiddly. We didn't include a MaskRCNN implementation in our repository because it requires a lot of time to implement. Instead, we used the Matterport version, as can be accessed in the link below:

https://github.com/matterport/Mask_RCNN

Here, we used `(8,16,32,64,128)` as RPN_ANCHOR_SCALES. We also changed `RPN_NMS_THRESHOLD` to 0.8 and `ROI_POSITIVE_RATIO` to 0.4. We used `DETECTION_MAX_INSTANCES` = 350.

Other notes- we used ResNet50 backbone and performed random crop to get the 256x256 input image. Then, during training we trained all of the network in one go, but used a similar learning rate schedule that we used for our other networks. We also used the same augmentation pipeline as other networks.

I hope this helps.

**Comment by GekFreeman** [comment]
Thanks so much! I'll try your settings,  and I believe they can help me a lot.

**Comment by haiqinzhong** [comment]
@GekFreeman ,have you reproduce the result on mask_rcnn?

**Comment by GekFreeman** [comment]
No...there is still a big gap
