### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by uzunper** [vqdang/hover_net#42]
Hi, 
Thank you for your study. I could not understand how to update the following lines in config.py (line 74 and 75 of config.py). Can you indicate which data will be given to train_dir and valid_dir? 

        self.data_ext = '.npy' 
        # list of directories containing validation patches. 
        # For both train and valid directories, a comma separated list of directories can be used
        self.train_dir = ['../../../CoNSeP/train/%s/'  % data_code_dict[self.model_type]]
        self.valid_dir = ['../../../CoNSeP/valid/%s/' % data_code_dict[self.model_type]]

Thank you

**Comment by simongraham** [comment]
Hi @uzunper 

Lines 74 and 75 simply state the path to your training and validation directories. This is in the form of a list because it enables you to put multiple directory paths if you wish. For example, if for self.train_dir, you put 

```
self.train_dir = [root_path + 'A/' , root_path + 'B/']
```

then that would combine directories A and B to ge the overall training set. Typically however only one directory is used in this list.

The directory should combine a numpy file for each patch, where the numpy patches are extracted using `extract_patches.py`. So therefore, you first need to generate the patches before they can be used by the code. `extract_patches.py` will read in the image and the label and then create patches and save in a directory. This is the directory that lines 74 and 75 of `config.py` need to point to.

**Comment by simongraham** [comment]
I am closing this as it should solve you issue. Please reopen the issue if you have any further questions specifically about this topic.

**Comment by uzunper** [comment]
So I will use extract_patches.py. Thank you very much for your answer!

Simon Graham <notifications@github.com>, 7 May 2020 Per, 04:36 tarihinde
şunu yazdı:
