### ISSUE TITLE
on MoNuSAC dataset

### ISSUE THREAD

**Issue by Michaelsqj** [vqdang/hover_net#46]
![image](https://user-images.githubusercontent.com/47425492/82903408-7c248b00-9f93-11ea-984e-95a86cef7348.png)
Hi! Sorry to bother again. I trained the hovernet on MoNuSAC dataset and I encountered this problem. Where might go wrong?

**Comment by Michaelsqj** [comment]
![IMG_0448](https://user-images.githubusercontent.com/47425492/82904797-8c3d6a00-9f95-11ea-9932-c0aab182dcca.PNG)

**Comment by Michaelsqj** [comment]
Besides, I'm curious about two questions,
1.The input shape to the hover net is 270*270, why the shape of the patch should be 540*540
2.How did you address the problem that some images in MoNuSAC is smaller than 540*540?  I pad the image smaller than 540*540 before xtractor.extract() in extract_patches.py. Is this correct?
3.Should I pad the image with zeros or anything else? If I pad the image with 'reflect' or 'mirror', I think the instance map might be affected.
Thank you so much for helping me!

**Comment by simongraham** [comment]
Hi,

The above error is given when you are removing 0 from a list, where 0 doesn't exist. This would only happen when your labels do not contain background. However, there should always be some background in your patches, so i would suggest that you should double check your patches. You can use `python train.py --view='train'` to visualise the training patches. 

In response to your second question, we extracted a patch double the size of the size of the input to the network. When augmenting, there are inevitable issues at the borders when applying transformations that do not work nicely with square matrices. For example, picture what happens at the corners when rotating an image by 45 degrees. If we transform a larger image and then perform a central crop we ensure that we still have a valid part of the image as input to the network

**Comment by vqdang** [comment]
Hi, 

For your 3rd question, the instance map calculation is done upon the **original input size**, which is at 540x540. Then, a fix is applied to remove the duplicated instance effect of `reflect` padding. 
https://github.com/vqdang/hover_net/blob/f5419068da18a338509854b4f8260ee901bff88e/src/loader/augs.py#L29

Hence, the only remaining effect would be weird instance cut off coming from black background etc due to shearing / rotation. And, as long as you provide the original image of large enough size, we don't need to do extra fix, we only need to crop it at the central.

Also, another point needs to stress here is that this only works because the **original input size** > output mask shape enough. And, that wouldn't be the case otherwise, because the current fix wouldn't amend the instance directly split at the boundary of mask shape (mirror padding will create a continuous ID chunk), and these cases are much harder and more computationally expensive to fix too.
