### ISSUE TITLE
Extraction of vertical and horizontal density maps

### ISSUE THREAD

**Issue by ChristianEschen** [vqdang/hover_net#7]
Hi

Thank you once more for the nice code. 
I cannot see how you precompute the vertical and horizontal maps.
Can you guide me to the relevant part of the code :-) ?

best regards
Christian

**Comment by vqdang** [comment]
Hi again, 

This is actually a good question because I don't think we put how to find it.

You can find all the things related to ground truth generation within 
>https://github.com/vqdang/hover_net/blob/master/src/loader/augs.py
The XY map is generated on the flight as an augmentation via 
https://github.com/vqdang/hover_net/blob/392becba9bc3760d2815574451bf73d0642a44e0/src/loader/augs.py#L184
However, to correctly know how to use it, please check the augmentation ordering  
https://github.com/vqdang/hover_net/blob/392becba9bc3760d2815574451bf73d0642a44e0/src/config.py#L151
and reconstruct it to fit your need when making your pytorch code.

Hope this will be of help to you and others.

**Comment by Ghulam111** [comment]
@vqdang  i wanted to know why did we train our model to find x y distance maps if we can generate them via augmentation process mentioned in this thread.
