### ISSUE TITLE
Im getting a Key Error Please Help

### ISSUE THREAD

**Issue by Thejas05** [vqdang/hover_net#77]
----------------EPOCH 1
  0% 0/49 [00:00<?, ?it/s['', {'Batch': nan, 'EMA': nan}]]Traceback (most recent call last):
  File "run_train.py", line 296, in <module>
    trainer.run()
  File "run_train.py", line 277, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 256, in run_once
    main_runner.run(opt["nr_epochs"])
  File "/content/drive/My Drive/Projects/hover_net-pytorch/run_utils/engine.py", line 182, in run
    step_output = self.run_step(data_batch, step_run_info)
  File "/content/drive/My Drive/Projects/hover_net-pytorch/models/hovernet/run_desc.py", line 48, in train_step
    true_tp = batch_data["tp_map"]
KeyError: 'tp_map'

**Comment by vqdang** [comment]
@Thejas05  This error is because you are training with model defined for `nuclei type classification` while your generated data is not.

https://github.com/vqdang/hover_net/blob/b527c004d51c7515f5f08f59c2e0597f7171dd02/config.py#L30
https://github.com/vqdang/hover_net/blob/b527c004d51c7515f5f08f59c2e0597f7171dd02/models/hovernet/opt.py#L34
https://github.com/vqdang/hover_net/blob/b527c004d51c7515f5f08f59c2e0597f7171dd02/models/hovernet/opt.py#L68

`nr_type=None` means not  `nuclei type classification`  mode.

**Comment by Thejas05** [comment]
Thankyou so much for the reply! i corrected it and its working thank you
