### ISSUE TITLE
resizing before run inference

### ISSUE THREAD

**Issue by liux0614** [vqdang/hover_net#90]
Dear @simongraham,
Assume I have test images from `consep` dataset, and the original size of the images are 1000x1000. I was just wondering if resizing to 270 is needed for test images before run inference as I did not see any resizing operations in `run_infer.py`. I also tried to feed the original images directly without any preprocessing operations, I got `Silent Crash` error.

**Comment by vqdang** [comment]
For tile, the code performs internal padding and patching to create image patches
https://github.com/vqdang/hover_net/blob/08456787d033d4bb1deff478313a8e305805845d/infer/tile.py#L46

For error, you need to provide more details on what you did. `Silent Error` means post proc multiproc crashed due to sthg. So you may need to set the #worker for post proc to 0 for debugging.

**Comment by liux0614** [comment]
I set `nr_post_proc_workers=0`, I got the following error.
![image](https://user-images.githubusercontent.com/3401577/104855433-c53a9e00-58da-11eb-8ba6-505ca6099bab.png)

**Comment by vqdang** [comment]
@liux0614 I could not reproduce your error. 
![image](https://user-images.githubusercontent.com/24943262/105026946-0e0f6580-5a47-11eb-94cd-95919d3c79c7.png)

It doesnt make sense for me for the above error to appear. You may need to drop in to the debug mode and check the shape of the `inst_bbox` and `inst_contour` when it crashed. `inst_bbox` should have shape 2x2 and `inst_contour` should have shape Nx2 and N > 3. I will push another commit to force ignore certain shape and hopefully yours can run.

Again, this should not happene because both the weight are the same.

**Comment by vqdang** [comment]
Close due to inactivity.
